// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgORmc1eE1HVpGxMzC_VZLfiiDaY0CKOs',
    appId: '1:924752740827:web:af23e814d391bda02267fe',
    messagingSenderId: '924752740827',
    projectId: 'eshoes-aa094',
    authDomain: 'eshoes-aa094.firebaseapp.com',
    storageBucket: 'eshoes-aa094.appspot.com',
    measurementId: 'G-F6S0MXPH5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjoXDA3FEG-PIQs0seI3iysquti_zHdFM',
    appId: '1:924752740827:android:8405f4f6ebd43ebc2267fe',
    messagingSenderId: '924752740827',
    projectId: 'eshoes-aa094',
    storageBucket: 'eshoes-aa094.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa8vPoJ3jfIwkO5lriBe2a0Qe65JqmcpQ',
    appId: '1:924752740827:ios:b019e6af7ab5a30c2267fe',
    messagingSenderId: '924752740827',
    projectId: 'eshoes-aa094',
    storageBucket: 'eshoes-aa094.appspot.com',
    iosClientId: '924752740827-hdjfvhjtr7s908ufhq5qncj3rrhhng1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.emartApp',
  );
}
